#! /bin/bash
#SBATCH -A see200002p
#SBATCH -p GPU-shared
#SBATCH --gpus=v100-32:1
#SBATCH -J myjob
#SBATCH -N 1
#SBATCH -n 4
#SBATCH -t 24:00:00

echo "Test with 2^31 - 1 presicion"
echo "Testing OpenACC GPU time"
./cOpenGPU
