#! /bin/bash
#SBATCH -A see200002p
#SBATCH -p GPU-shared
#SBATCH --gpus=v100-32:1
#SBATCH -J myjob
#SBATCH -N 1
#SBATCH -n 4
#SBATCH -t 24:00:00


echo "Generating nsys and ncu file for cOpenGPU"
nsys profile -o pi_OpenACC_GPU_nsys --trace openacc ./cOpenGPU

ncu --set full -o pi_OpenACC_GPU_ncu -f ./cOpenGPU
